<testsuite errors="4" failures="0" name="" tests="10" time="0.001">
<testcase classname="unittest.loader._FailedTest" name="test_battle" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_battle
Traceback (most recent call last):
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\tests\test_battle.py", line 2, in &lt;module>
    from battle import Battle
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\battle.py", line 6, in &lt;module>
    from poke_team import Action, PokeTeam, Criterion
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\poke_team.py", line 4, in &lt;module>
    from array_list import ArrayList                # Module for accessing ArrayList properties.
ModuleNotFoundError: No module named 'array_list'

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_poke_team" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_poke_team
Traceback (most recent call last):
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\tests\test_poke_team.py", line 1, in &lt;module>
    from poke_team import Action, Criterion, PokeTeam
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\poke_team.py", line 4, in &lt;module>
    from array_list import ArrayList                # Module for accessing ArrayList properties.
ModuleNotFoundError: No module named 'array_list'

</error>
</testcase>
<testcase classname="test_pokemon.TestPokemon" name="test_venusaur_stats" time="0.000"/>
<testcase classname="test_pokemon_base.TestPokemonBase" name="test_cannot_init" time="0.000"/>
<testcase classname="test_pokemon_base.TestPokemonBase" name="test_evolution" time="0.000"/>
<testcase classname="test_pokemon_base.TestPokemonBase" name="test_hp" time="0.000"/>
<testcase classname="test_pokemon_base.TestPokemonBase" name="test_level" time="0.000"/>
<testcase classname="test_pokemon_base.TestPokemonBase" name="test_status" time="0.000"/>
<testcase classname="unittest.loader._FailedTest" name="test_tournament" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_tournament
Traceback (most recent call last):
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\tests\test_tournament.py", line 2, in &lt;module>
    from tournament import Tournament
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\tournament.py", line 7, in &lt;module>
    from poke_team import PokeTeam
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\poke_team.py", line 4, in &lt;module>
    from array_list import ArrayList                # Module for accessing ArrayList properties.
ModuleNotFoundError: No module named 'array_list'

</error>
</testcase>
<testcase classname="unittest.loader._FailedTest" name="test_tower" time="0.000">
<error type="ImportError">ImportError: Failed to import test module: test_tower
Traceback (most recent call last):
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\henry\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\tests\test_tower.py", line 2, in &lt;module>
    from poke_team import Criterion, PokeTeam
  File "C:\Amy\MIPS ASSIGNMENT\fit-1008-group-30\poke_team.py", line 4, in &lt;module>
    from array_list import ArrayList                # Module for accessing ArrayList properties.
ModuleNotFoundError: No module named 'array_list'

</error>
</testcase>
</testsuite>
